/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.beans.PropertyVetoException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.dao.FunctionsDAO;
import model.dto.Functions;

/**
 *
 * @author USER
 */
public class FunctionInF extends javax.swing.JInternalFrame {

    FunctionsDAO dao = null;
    int rowSelected = -1;

    /**
     * Creates new form FunctionInF
     */
    public FunctionInF() {
        initComponents();
        dao = new FunctionsDAO();
        loadTableFunctions(dao.readAll());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        spnMain = new javax.swing.JScrollPane();
        tblMain = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtFunctionsId = new javax.swing.JTextField();
        txtFunctionName = new javax.swing.JTextField();
        txtDescription = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Functions"));
        jPanel1.setAutoscrolls(true);

        tblMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMainMouseClicked(evt);
            }
        });
        spnMain.setViewportView(tblMain);

        jLabel1.setText("FunctionsId :");

        jLabel2.setText("FunctionName :");

        jLabel3.setText("Description :");

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spnMain, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCreate)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                                    .addComponent(txtFunctionName)
                                    .addComponent(txtFunctionsId)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(btnRefresh)
                                .addGap(43, 43, 43)
                                .addComponent(btnUpdate)
                                .addGap(55, 55, 55)
                                .addComponent(btnDelete)))))
                .addGap(81, 81, 81))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFunctionsId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFunctionName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate)
                    .addComponent(btnRefresh)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addGap(43, 43, 43)
                .addComponent(spnMain, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMainMouseClicked
        // TODO add your handling code here:
        rowSelected = tblMain.getSelectedRow();
        int functionsid = (int) tblMain.getValueAt(rowSelected, 0);
        String functionname = (String) tblMain.getValueAt(rowSelected, 1);
        String description = (String) tblMain.getValueAt(rowSelected, 2);

        txtFunctionsId.setText(String.valueOf(functionsid));
        txtFunctionsId.setEditable(false);
        txtFunctionName.setText(functionname);
        txtDescription.setText(description);
    }//GEN-LAST:event_tblMainMouseClicked

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        int functionsid = Integer.parseInt(txtFunctionsId.getText().trim());
        String functionname = txtFunctionName.getText().trim();
        String description = txtDescription.getText().trim();
        Functions f = new Functions(functionsid, functionname, description);
        if (dao.create(f) != null) {
            JOptionPane.showMessageDialog(this, "Success");
            loadTableFunctions(dao.readAll());
            rowSelected = -1;
        } else {
            JOptionPane.showMessageDialog(this, "failed");
        }
    }//GEN-LAST:event_btnCreateActionPerformed
    private void loadTableFunctions(List<Functions> readAll) {
        Vector colunm = new Vector();
        colunm.add("FUNCTIONSID");
        colunm.add("FUNCTIONNAME");
        colunm.add("DESCRIPTION");
        Vector rows = new Vector();
        for (Functions f : readAll) {
            Vector row = new Vector();
            row.add(f.getFunctionsid());
            row.add(f.getFunctionname());
            row.add(f.getDescription());
            rows.add(row);
        }
        tblMain.setModel(new DefaultTableModel(rows, colunm));
        tblMain.updateUI();
        spnMain.setViewportView(this.tblMain);
    }
    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        txtFunctionsId.setEditable(true);
        txtFunctionsId.setText("");
        txtFunctionName.setText("");
        txtDescription.setText("");
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        rowSelected = tblMain.getSelectedRow();
        if (rowSelected == -1) {
            JOptionPane.showMessageDialog(this, "Please choose row to update");
        } else {
            int functionsid = (int) tblMain.getValueAt(rowSelected, 0);
            String functionname = txtFunctionName.getText().trim();
            String description = txtDescription.getText().trim();
            Functions f = new Functions(functionsid, functionname, description);
            if (dao.update(f) != null) {
                JOptionPane.showMessageDialog(this, "Updated");
                loadTableFunctions(dao.readAll());
            } else {
                JOptionPane.showMessageDialog(this, "Not update id: " + functionsid);
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if (rowSelected == -1) {
            JOptionPane.showMessageDialog(this, "Please choose row to delete");
        } else {
            int functionsid = (int) tblMain.getValueAt(rowSelected, 0);
            String functionname = (String) tblMain.getValueAt(rowSelected, 1);
            String description = (String) tblMain.getValueAt(rowSelected, 2);
            Functions f = new Functions(functionsid, functionname, description);
            if (dao.delete(functionsid)) {
                JOptionPane.showMessageDialog(this, "Deleted");
                loadTableFunctions(dao.readAll());
            } else {
                JOptionPane.showMessageDialog(this, "Not delete id: " + functionsid);
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane spnMain;
    private javax.swing.JTable tblMain;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtFunctionName;
    private javax.swing.JTextField txtFunctionsId;
    // End of variables declaration//GEN-END:variables
}
