/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.dao.UsersDAO;
import model.dto.Users;

/**
 *
 * @author USER
 */
public class UsersInF extends javax.swing.JInternalFrame {

    UsersDAO dao = null;
    int rowSelected = -1;

    /**
     * Creates new form UsersInF
     */
    public UsersInF() {
        initComponents();
        dao = new UsersDAO();
        loadTableUsers(dao.readAll());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtUsersName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtRoleId = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        spnMain = new javax.swing.JScrollPane();
        tblMain = new javax.swing.JTable();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Users"));

        jLabel1.setText("Id :");

        jLabel2.setText("UsersName :");

        jLabel3.setText("Password :");

        jLabel4.setText("RoleId :");

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        tblMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMainMouseClicked(evt);
            }
        });
        spnMain.setViewportView(tblMain);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(spnMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addGap(48, 48, 48)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                                .addComponent(txtUsersName)
                                .addComponent(txtPassword)
                                .addComponent(txtRoleId)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(88, 88, 88)
                            .addComponent(btnCreate)
                            .addGap(46, 46, 46)
                            .addComponent(btnRefresh)
                            .addGap(50, 50, 50)
                            .addComponent(btnUpdate)
                            .addGap(38, 38, 38)
                            .addComponent(btnDelete))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUsersName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtRoleId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate)
                    .addComponent(btnRefresh)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addGap(80, 80, 80)
                .addComponent(spnMain, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txtId.getText().trim());
        String usersname = txtUsersName.getText().trim();
        String password = txtPassword.getText().trim();
        int roleid = Integer.parseInt(txtRoleId.getText().trim());
        Users u = new Users(id, usersname, password, roleid);
        if (dao.create(u) != null) {
            JOptionPane.showMessageDialog(this, "Success");
            loadTableUsers(dao.readAll());
            rowSelected = -1;
        } else {
            JOptionPane.showMessageDialog(this, "failed");
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        txtId.setEditable(true);
        txtId.setText("");
        txtUsersName.setText("");
        txtPassword.setText("");
        txtRoleId.setText("");
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        rowSelected = tblMain.getSelectedRow();
        if (rowSelected == -1) {
            JOptionPane.showMessageDialog(this, "Please choose row to update");
        } else {
            int id = (int) tblMain.getValueAt(rowSelected, 0);
            String usersname = txtUsersName.getText().trim();
            String password = txtPassword.getText().trim();
            int roleid = Integer.parseInt(txtRoleId.getText().trim());
            Users u = new Users(id, usersname, password, roleid);
            if (dao.update(u) != null) {
                JOptionPane.showMessageDialog(this, "Updated");
                loadTableUsers(dao.readAll());
            } else {
                JOptionPane.showMessageDialog(this, "Not update id: " + id);
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if (rowSelected == -1) {
            JOptionPane.showMessageDialog(this, "Please choose row to delete");
        } else {
            int id = (int) tblMain.getValueAt(rowSelected, 0);
            String usersname = (String) tblMain.getValueAt(rowSelected, 1);
            String password = (String) tblMain.getValueAt(rowSelected, 2);
            int roleid = (int) tblMain.getValueAt(rowSelected, 3);
            Users u = new Users(id, usersname, password, roleid);
            if (dao.delete(id)) {
                JOptionPane.showMessageDialog(this, "Deleted");
                loadTableUsers(dao.readAll());
            } else {
                JOptionPane.showMessageDialog(this, "Not delete id: " + id);
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMainMouseClicked
        // TODO add your handling code here:
        rowSelected = tblMain.getSelectedRow();
        int id = (int) tblMain.getValueAt(rowSelected, 0);
        String usersname = (String) tblMain.getValueAt(rowSelected, 1);
        String password = (String) tblMain.getValueAt(rowSelected, 2);
        int roleid = (int) tblMain.getValueAt(rowSelected, 3);

        txtId.setText(String.valueOf(id));
        txtId.setEditable(false);
        txtUsersName.setText(usersname);
        txtPassword.setText(password);
        txtRoleId.setText(String.valueOf(roleid));
    }//GEN-LAST:event_tblMainMouseClicked


    private void loadTableUsers(List<Users> readAll) {
        Vector colunm = new Vector();
        colunm.add("ID");
        colunm.add("USERSNAME");
        colunm.add("PASSWORD");
        colunm.add("ROLEID");
        Vector rows = new Vector();
        for (Users u : readAll) {
            Vector row = new Vector();
            row.add(u.getId());
            row.add(u.getUsersname());
            row.add(u.getPassword());
            row.add(u.getRoleid());
            rows.add(row);
        }
        tblMain.setModel(new DefaultTableModel(rows, colunm));
        tblMain.updateUI();
        spnMain.setViewportView(this.tblMain);        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane spnMain;
    private javax.swing.JTable tblMain;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtRoleId;
    private javax.swing.JTextField txtUsersName;
    // End of variables declaration//GEN-END:variables
}
